"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
$time\
$cmd_duration\
$line_break\
$character"""

[os]
disabled = false
format = '[$symbol ]($style)'
style = "fg:red"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:red bold"
style_root = "fg:red bold"
format = '[$user ]($style)'

[directory]
style = "fg:blue bold"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:yellow"
format = '[$symbol $branch ]($style)'

[git_status]
style = "fg:yellow"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "fg:green"
format = '[$symbol ($version) ]($style)'

[c]
symbol = " "
style = "fg:green"
format = '[$symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:green"
format = '[$symbol ($version) ]($style)'

[golang]
symbol = ""
style = "fg:green"
format = '[$symbol ($version) ]($style)'

[php]
symbol = ""
style = "fg:green"
format = '[$symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:green"
format = '[$symbol ($version) ]($style)'

[kotlin]
symbol = ""
style = "fg:green"
format = '[$symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "fg:green"
format = '[$symbol ($version) ]($style)'

[python]
symbol = ""
style = "fg:green"
format = '[$symbol ($version)(\(#$virtualenv\)) ]($style)'

[docker_context]
symbol = ""
style = "fg:cyan"
format = '[$symbol ($context) ]($style)'

[conda]
symbol = "  "
style = "fg:cyan"
format = '[$symbol $environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "fg:purple"
format = '[ $time ]($style)'

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:purple)'
vimcmd_replace_symbol = '[❮](bold fg:purple)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = "[ in $duration ]($style)"
style = "fg:purple"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[line_break]
disabled = false